theme: cayman
title: Gary's Site
description: Recording my work, studies, and career journey
author: Gary

header_pages:
  - index.md
  - projects.md
  - ai-notes.md
  - blog.md
  - resume.md
  - about.md
